title: A career in BIM
description: My notes on a career in BIM and engineering.
theme: minima
author: Gaurav Patil

github_username: gauravpatil001
linkedin_username: gauravpatil001

plugins:
  - jekyll-feed
