title: Model & Method
description: Essays on BIM, engineering practice, and professional growth.
theme: minima
author: Gaurav Patil

github_username: gauravpatil001
linkedin_username: gauravpatil001

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: page
